name: Build and deploy Java project to Azure Function App - demo-func-3456

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: demo-func-3456
  JAVA_VERSION: '17'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      # Compila y empaqueta el Function App y genera el ZIP en target/azure-functions/<app>.zip
      - name: Build with Maven (package)
        run: mvn -B -ntp -DskipTests clean package

      # (Opcional) Lista para confirmar que el ZIP existe
      - name: List packaged artifacts
        run: ls -R target/azure-functions || true

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: Production
          # APUNTA al ZIP generado por el plugin de Azure Functions para Maven
          package: target/azure-functions/${{ env.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_76EB0F73C2DD4909ABC5C4FA5B51EE43 }}
